CREATE DATABASE IF NOT EXISTS Stencil;
#DROP DATABASE Stencil;
USE Stencil;

CREATE TABLE IF NOT EXISTS Aluno(
	idAluno INT PRIMARY KEY AUTO_INCREMENT,
    nomeAluno VARCHAR(25) NOT NULL UNIQUE,
    nick VARCHAR(25),
    xp INT NOT NULL,
    skin VARCHAR(255) NOT NULL,
    ofensiva INT
);

CREATE TABLE IF NOT EXISTS Professores(
	idProf INT PRIMARY KEY AUTO_INCREMENT,
    nomeProf VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS Turma(
	idTurma INT PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE IF NOT EXISTS Turma_Aluno(
	id_Aluno INT,
    FOREIGN KEY (id_Aluno) REFERENCES Aluno (idAluno)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    id_Turma INT PRIMARY KEY,
    FOREIGN KEY (id_Turma) REFERENCES Turma (idTurma)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Turma_Prof(
	id_Prof INT,
    FOREIGN KEY (id_Prof) REFERENCES Professores (idProf)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    id_Turma INT PRIMARY KEY,
    FOREIGN KEY (id_Turma) REFERENCES Turma (idTurma)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Login_Prof(
	id_Prof INT,
    FOREIGN KEY (id_Prof) REFERENCES Professores (idProf)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    userProf VARCHAR(30) PRIMARY KEY NOT NULL UNIQUE,
    senhaProf BLOB
);

CREATE TABLE IF NOT EXISTS Login_Aluno(
	id_Aluno INT,
    FOREIGN KEY (id_Aluno) REFERENCES Aluno (idAluno)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    userAluno VARCHAR(30) PRIMARY KEY NOT NULL UNIQUE,
    senhaAluno BLOB
);